### ISSUE TITLE
supersonic drawer failed

### ISSUE THREAD

**Issue by zhulongzheng** [AppGyver/steroids#738]
When I have the drawer config in the structure.coffee
```
drawers:
    left:
      id: "leftDrawer"
      location: "example#drawer"
      showOnAppLoad: false
    options:
      animation: "swingingDoor"
```
I still need the `supersonic.ui.drawers.init`?

And when I init and open within a method of a controller like:
```
supersonic.ui.views.find('example#drawer').then(function(leftDrawer) {
    supersonic.logger.log(leftDrawer)

    supersonic.ui.drawers.init(leftDrawer)
    supersonic.ui.drawers.open()
})
```

I got this in the logs:
```
{"options":{"location":"example#drawer","id":"example#drawer"},"id":"example#drawer","location":"example#drawer","_webView":{"prefixName":"webview","validEvents":["created","preloaded","unloaded"],"location":"http://localhost/app/example/drawer.html","params":{"http://localhost/app/example/drawer.html":"undefined"}}}
supersonic.ui.drawers.init rejected: {}
```
