### ISSUE TITLE
supersonic.ui.drawers.open("left") throws an invalid rejection on Android

### ISSUE THREAD

**Issue by Gniller** [AppGyver/steroids#838]
I've declared my drawer as the following within my structure.coffee:

```
drawers:
     left:
       id: "left"
       location: "common#menu"
       showOnAppLoad: false
     options:
       animation: "swingingDoor"
```

Then i try to open it with the following code programmatically:

```
supersonic.ui.drawers.open("left", {
    onSuccess: function () {
        console.log("Drawer opening...");
    },
    onFailure: function (error) {
        console.error("Could not show the drawer: " + error.errorDescription);
    }
});
```

Now in IOS, this works perfectly fine. In Android however, i receive the following error:

```
supersonic.logger.error: supersonic.ui.drawers.open rejected: There are no drawers 
```

The funny thing is, when i drag the drawer from the side, it opens just fine. The issue is with the programmatically opening of the drawer (a navbar function in my case). The identical function works for IOS.

I know drawers can't be declared on runtime on Android (yet), hence the structure.coffee but i assume what i try to do here is already suppossed to work?

Any feedback is appriciated!

Thanks,

Robin
